# Generated by Django 2.2.4 on 2019-09-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svetlyachokshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, verbose_name="Сума(необов'язково, рахує самостійно)")),
                ('second_name', models.CharField(max_length=200, verbose_name='Прізвище')),
                ('first_name', models.CharField(max_length=200, verbose_name='Імя')),
                ('last_name', models.CharField(max_length=200, verbose_name='Побатькові')),
                ('phone_number', models.CharField(max_length=9, verbose_name='Номер телефону +380')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Електрона пошта')),
                ('buying_type', models.CharField(choices=[('nova_poshta', 'Нова пошта'), ('ukr_poshta', 'Укр-пошта')], max_length=40, verbose_name='Спосіб доставки')),
                ('address', models.CharField(max_length=255, verbose_name='адреса')),
                ('status', models.CharField(choices=[('AIP_status', 'Прийнятий в обробку'), ('IP_status', 'В обробці'), ('PAID_status', 'Оплачено')], default='AIP_status', max_length=100, verbose_name='Статус')),
                ('comments', models.TextField(blank=True, verbose_name='Коментарь')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
