# Generated by Django 2.2.4 on 2019-09-15 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20190915_0752'),
        ('svetlyachokshop', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cart.Cart', verbose_name='Корзина'),
            preserve_default=False,
        ),
    ]
