# Generated by Django 2.2.4 on 2019-09-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svetlyachokshop', '0004_auto_20190915_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Коментарь'),
        ),
    ]
