# Generated by Django 2.2.4 on 2019-09-15 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svetlyachokshop', '0005_auto_20190915_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Cart', verbose_name='Корзина'),
        ),
    ]
