"""
Django settings for svetlyachokshop project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'bp(v!g84sp)abnxuke$v57_tjb++elmb(mf80+6rgox%91kgam'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
#Internationalization
    'parler',
#Admin models 
    'easy_thumbnails',
    'filer',
    'mptt',
#Media
    'storages',
#Cart
    'cart',
#Bootstrap
    'crispy_forms',
#Edit post castom
    'django_summernote',
    'svetlyachokshop',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    'django.middleware.locale.LocaleMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'svetlyachokshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'svetlyachokshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'sveta_db',
#         'USER':'sveta',
#         'PASSWORD':'sveta_09_shop',
#         'HOST':'localhost',
#         'PORT':'',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'uk'

from django.utils.translation import ugettext_lazy as _

LANGUAGES = (
    ('ru', _('Russian')),
    ('uk', _('Ukrainian')),
)

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# parler setting
PARLER_DEFAULT_LANGUAGE_CODE = 'uk'

PARLER_LANGUAGES = {
    None: (
        {'code': 'uk',},
        {'code': 'ru',},
    ),
    'default': {
        'fallback': 'uk',             # defaults to PARLER_DEFAULT_LANGUAGE_CODE
        'hide_untranslated': False,   # the default; let .active_translations() return fallbacks too.
    }
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static_in_dev'),
)

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]
###################### batariki setting app
THUMBNAIL_HIGH_RESOLUTION = True

THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    #'easy_thumbnails.processors.scale_and_crop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters',
)
CRISPY_TEMPLATE_PACK = 'bootstrap4'



EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'svetlyachok.handmade@gmail.com'
EMAIL_HOST_PASSWORD = 'Svetlana1309#'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# DROPBOX_OAUTH2_TOKEN='2OtGfbdx0JAAAAAAAAAATLc4l5ZdUcp77eyx5R98S8Xi5-1uHUBiepD8Yom53QI6'
DROPBOX_OAUTH2_TOKEN='2OtGfbdx0JAAAAAAAAAACcFYZNJriL9XjXggR0z4SEU_5qX-wJwzBjBn3D6-qnyP'
DROPBOX_ROOT_PATH='/media/'
DEFAULT_FILE_STORAGE='storages.backends.dropbox.DropBoxStorage'