# Generated by Django 2.2.4 on 2019-09-15 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svetlyachokshop', '0002_order'),
        ('cart', '0006_auto_20190915_0746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('cart',), 'verbose_name': 'item 2', 'verbose_name_plural': 'items 2'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='object_id',
        ),
        migrations.AddField(
            model_name='item',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='svetlyachokshop.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, verbose_name='unit price'),
        ),
        migrations.DeleteModel(
            name='Item2',
        ),
    ]
